services:
  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    networks:
    - app-network
  
  postgres_sgbd:
    image: postgres:16-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: sys_dba_master
      POSTGRES_PASSWORD: 1234
      TZ: America/Sao_Paulo
      PGTZ: America/Sao_Paulo
    volumes:
      - .data-base/postgres-data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  postgres_data:
  pgadmin_data:

networks:
  app-network:
    driver: bridge