CREATE DATABASE to_do_list_db;

CREATE ROLE to_do_list_app WITH LOGIN PASSWORD '1234';
GRANT CONNECT ON DATABASE to_do_list_db TO to_do_list_app;

CREATE ROLE app_orchestrator;
GRANT app_orchestrator TO to_do_list_app;

REVOKE ALL ON SCHEMA public FROM PUBLIC;

ALTER DEFAULT PRIVILEGES REVOKE ALL ON TABLES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SEQUENCES FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON FUNCTIONS FROM PUBLIC;
ALTER DEFAULT PRIVILEGES REVOKE ALL ON SCHEMAS FROM PUBLIC;
